---
- hosts: all
  tasks:
    - name: install kerberos
      command: yum install -y krb5-server krb5-workstation pam_krb5
    - name: removing file /var/kerberos/krb5kdc/kdc.conf
      shell: |
        rm -rf /var/kerberos/krb5kdc/kdc.conf
        touch /var/kerberos/krb5kdc/kdc.conf
    - name: Insert /var/kerberos/krb5kdc/kdc.conf
      blockinfile:
        path: /var/kerberos/krb5kdc/kdc.conf
        block: |
          [kdcdefaults]
           kdc_ports = 88
           kdc_tcp_ports = 88

          [realms]
           EXAMPLE.COM = {
           #master_key_type = aes256-cts
           acl_file = /var/kerberos/krb5kdc/kadm5.acl
           dict_file = /usr/share/dict/words
           admin_keytab = /var/kerberos/krb5kdc/kadm5.keytab
           supported_enctypes = aes256-cts:normal aes128-cts:normal des3-hmac-sha1:normal arcfour-hmac:normal camellia256-cts:normal                     camellia128-cts:normal des-hmac-sha1:normal des-cbc-md5:normal des-cbc-crc:normal
            }

    - name: removing file /var/kerberos/krb5kdc/kadm5.acl
      shell: |
        rm -rf /var/kerberos/krb5kdc/kadm5.acl
        touch /var/kerberos/krb5kdc/kadm5.acl
    - name: Insert /var/kerberos/krb5kdc/kadm5.acl
      blockinfile:
        path: /var/kerberos/krb5kdc/kadm5.acl
        block: |
          */admin@EXAMPLE.COM *
    - name: removing file /var/kerberos/krb5kdc/kadm5.acl
      shell: |
        rm -rf /etc/krb5.conf
        touch /etc/krb5.conf
    - name: Insert /etc/krb5.conf
      blockinfile:
        path: /etc/krb5.conf
        block: |
          # Configuration snippets may be placed in this directory as well
          includedir /etc/krb5.conf.d/

          [logging]
           default = FILE:/var/log/krb5libs.log
           kdc = FILE:/var/log/krb5kdc.log
           admin_server = FILE:/var/log/kadmind.log

          [libdefaults]
           dns_lookup_realm = false
           ticket_lifetime = 24h
           renew_lifetime = 7d
           forwardable = true
           rdns = false
           pkinit_anchors = FILE:/etc/pki/tls/certs/ca-bundle.crt
           default_realm = EXAMPLE.COM
           default_ccache_name = KEYRING:persistent:%{uid}

          [realms]
            EXAMPLE.COM = {
            kdc = node-1.kerberos.com
            admin_server = node-1.kerberos.com
           }
 
          [domain_realm]
           .example.com = EXAMPLE.COM
           example.com = EXAMPLE.COM

    - name: create db and start service
      shell: |
        kdb5_util -P admin create -s -r EXAMPLE.COM
        systemctl start krb5kdc kadmin
        systemctl enable krb5kdc kadmin
        systemctl status krb5kdc
        systemctl status kadmin
        useradd ravi4
        echo "YourPassword" | passwd --stdin ravi4
        
    - name: adduser to pricipal and create keytab
      shell: |
       kadmin.local -q "addprinc -pw ravi41 ravi4" 
       kadmin.local -q "ktadd ravi4"
       chmod 777 /etc/krb5.keytab


